site_name: Receita Federal

repo_name: "2025.1-ReceitaFederal"
repo_url: "https://github.com/Requisitos-de-Software/2025.1-ReceitaFederal.git"
site_url: "https://requisitos-de-software.github.io/2025.1-ReceitaFederal/"

extra_css:
  - stylesheets/extra.css


theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark-blue  
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark-blue   
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/receita-federal.png 
  favicon: assets/receita-federal.ico
    

nav:
  - Início: index.md
  - Guias: 
      - Tutorial mkdocs: guias/tutorial-mkdocs.md
  - Apresentações: 
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Avaliação da apresentação grupo+1: apresentacoes/checklist-grupo7.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Avaliação da apresentação grupo+1: apresentacoes/checklist-grupo7-2.md
  - Inspeção: 
      - Entrega 01:
          - Grupo 6: inspecao/entrega01/inspecao-grupo6.md
          - Grupo +1: inspecao/entrega01/inspecao-grupo7.md
      - Entrega 02:
          - Grupo 6: inspecao/entrega02/inspecao-grupo6.md
          - Grupo +1: inspecao/entrega02/inspecao-grupo7-2.md
      - Entrega 03:
          - Grupo 6: inspecao/entrega03/inspecao-grupo6-3.md
          - Grupo +1: inspecao/entrega03/inspecao-grupo7-3.md
  - Atas: 
      - Ata 01 (11/04/2025): atas/ata1.md
      - Ata 02 (19/04/2025): atas/ata2.md
      - Ata 03 (21/04/2025): atas/ata3.md
      - Ata 04 (09/05/2025): atas/ata4.md
  - Pré-Rastreabilidade: 
      - RichPicture: pre-rastreabilidade/richpicture.md
  - Planejamento: 
      - App selecionado: planejamento/selecao-app.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap: planejamento/heatmap.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Executado: planejamento/cronograma-executado.md
  - Elicitação: 
      - Personas: elicitacao/personas.md
      - Storytelling: elicitacao/storytelling.md
      - Análise de documentos: elicitacao/analisededocumentos.md
      - Grupo de foco: elicitacao/grupodefoco.md
      - Priorização:
          - First Things First: elicitacao/priorizacao/ftf.md
          - MoSCoW: elicitacao/priorizacao/MoSCoW.md
          - 100$: elicitacao/priorizacao/100$.md
          - QFD: elicitacao/priorizacao/QFD.md
  - Modelagem: 
      - Cenários: modelagem/cenarios.md
      - Casos de uso: modelagem/casosdeuso.md
      - Léxicos: modelagem/lexicos.md
